### ISSUE TITLE
Unable to Install using pip

### ISSUE THREAD

**Issue by codemeleon** [spyder-ide/spyder.line_profiler#10]
Hi,
I am trying to install the plugin using pip. However, I am getting following error. 

pip install spyder.line_profiler
Collecting spyder.line_profiler
  **Could not find a version that satisfies the requirement spyder.line_profiler (from versions: )
No matching distribution found for spyder.line_profiler**

Thank you.

**Comment by Nodd** [comment]
Try the development version:
pip install git+git://github.com/spyder-ide/spyder-line-profiler.git
The pypi version is not up to date, I have to find some time to do it...

**Comment by jitseniesen** [comment]
@goanpeca Can you please look whether you have reserved the name `spyder.line_profiler` (with a dot) on PyPI? I tried to upload `spyder-line-profiler` (with a dash) but it complains that 
```
Package name conflicts with existing package 'spyder.line_profiler'
```
However, I cannot find anything about this existing package `spyder.line_profiler`

**Comment by goanpeca** [comment]
@jitseniesen yes I had it reserved, just deleted the project, could you try again?

**Comment by jitseniesen** [comment]
Thanks, that did the trick!

**Comment by jitseniesen** [comment]
Package landed in PyPI: https://pypi.python.org/pypi/spyder-line-profiler
