### ISSUE TITLE
Make conda package

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder.line_profiler#15]

**Comment by jitseniesen** [comment]
@ccordoba12 @goanpeca I could use some help here. The issue is that the conda package needs a test: https://github.com/conda-forge/staged-recipes/pull/2674#issuecomment-289444573 . The simplest test is `import spyder_line_profiler`. However, the plugin imports `spyder.plugins.runconfig` and that import requires running `qtawesome` in [spyder/plugins/runconfig.py:457](https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/runconfig.py#L457), which in turn requires a running QApplication. So, I added a line to create this (commit 3b115e7). The problem now is that the conda-forge Circle CI server does not have a running X server, so the test fails there.

If I delete the test from `conda.recipe/meta.yaml`, then conda-forge complains that there are no tests.

How to resolve this? Here are some possibilities I came up with:
1. Change [spyder/plugins/runconfig.py:457](https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/runconfig.py#L457) so that the call to `ima.icon()` is not done at import time but only when the class `RunConfigPage` is actually used.
1. Split the parts that I need for this plugin from `spyder/plugins/runconfig.py` to some `api` module so that this plugin no longer need to import the offending line.
1. Somehow write a test which does not need a running X server. Problem is, I don't know how. I tried to use xvfb but that is not available on conda-forge's CI servers.

Number 1 and 2 are not bad, but they require a change in spyder proper, meaning that the conda package for this plugin has to wait until that version of Spyder is released. 

So, what to do?

**Comment by jitseniesen** [comment]
I think I found a solution: use `imp.find_module()` to find an importable module without actually importing it. 

I still think that importing `spyder.plugin.runconfig` (and other Spyder modules) does too much work, but I'm not sure how much of a problem that actually is.

**Comment by ccordoba12** [comment]
My thoughts about your options:

1. This is a good, temporary solution for Spyder 3
2. This is the right solution for Spyder 4.

However, I don't know how easy it could be for you to maintain compatibility with both versions. So I think for now option 1. should be the way to go.

**Comment by goanpeca** [comment]
>Split the parts that I need for this plugin from spyder/plugins/runconfig.py to some api module so that this plugin no longer need to import the offending line.

Agreed!, but yeah for now that should do
