### ISSUE TITLE
saving profiling results

### ISSUE THREAD

**Issue by tmabraham** [spyder-ide/spyder.line_profiler#27]
Unless I am missing the feature or not using the plugin correctly, there is no way to save the profiling results. Could this feature be added?

**Comment by CAM-Gerlach** [comment]
![image](https://user-images.githubusercontent.com/17051931/40589503-e4e7df7c-61b3-11e8-8b9b-0712acb4469b.png)

**Comment by tmabraham** [comment]
@CAM-Gerlach I think there is a misunderstanding here. If I understand correctly, that is for the regular built-in spyder profiler. I am talking about the line-profiler.

**Comment by CAM-Gerlach** [comment]
Oh, sorry—my silly mistake.

**Comment by CAM-Gerlach** [comment]
Just FYI, it may be a bit for it to be added, since right now plugin development is paused to concentrate resources on the Spyder 4 release in six months or so. However, you're welcome to submit a PR adding it, and we'd be glad to review it.
