### ISSUE TITLE
Python 3.7 build for Spyder Line Profiler?

### ISSUE THREAD

**Issue by aarondodell** [spyder-ide/spyder.line_profiler#29]
I am curious if there will eventually be a Python 3.7 build for this package? I use the Line Profiler often, and want to upgrade to Python 3.7, but this is one of the key packages holding me back from doing so.

I've attached an image below showing the builds that exist for this project

![capture](https://user-images.githubusercontent.com/11433737/45459351-bc06ea00-b6ac-11e8-8341-3cacb1de3835.PNG)

Thanks!

**Comment by ccordoba12** [comment]
@jitseniesen, we should make the package `noarch` to avoid this problem in the future.

**Comment by jitseniesen** [comment]
@adodell Can you please try again? There should now be a package which is not tied to the particular Python version.

**Comment by aarondodell** [comment]
thank you both @jitseniesen and @ccordoba12 for the quick responses. Yes the Line Profiler is working perfectly now in Spyder with my Python 3.7 install.

you may want to do something similar for the Spyder-Notebook plugin, or all other plugins too. I notice that when I upgraded to Python 3.7 my Notebook plugin was removed. This is okay since I rarely use the Notebook plugin, but I know many other people use it.

![capture](https://user-images.githubusercontent.com/11433737/45500004-68d77a80-b732-11e8-9688-0e9167199cad.PNG)

Thank you both so much!

**Comment by ccordoba12** [comment]
> This is okay since I rarely use the Notebook plugin, but I know many other people use it.

Well, that's good to know!! We thought very few people were using it because it's a bit alpha and we haven't received too much bug reports about it.

But sure, we'll make it `noarch` too so it can work with any Python version.

> Thank you both so much!

You're welcome.
