### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by mettinger** [spyder-ide/spyder.line_profiler#3]
Hope this issue is easily fixable as I'd love to get this working in Spyder!

The command:

pip install spyder.line_profiler

results in the error:

Collecting spyder.line-profiler
  Could not find a version that satisfies the requirement spyder.line-profiler (from versions: )
No matching distribution found for spyder.line-profiler

**Comment by ccordoba12** [comment]
This is not ready for the public. We're still creating the infrastructure to make this possible, so please be patient :-)

This could be ready in two or three weeks.

**Comment by goanpeca** [comment]
@mettinger these plugins will be released with Spyder 3.0, I will add this in the readme.

Sorry for the inconvenience!

**Comment by mettinger** [comment]
Thank you for your work on this!  This will be a great addition to Spyder.

**Comment by darcyWang** [comment]
It's ok to sudo pip install pyspider ?

I still got Could not find a version that satisfies the requirement pyspider (from versions: )
No matching distribution found for pyspider

**Comment by ccordoba12** [comment]
There's still not a package available in PyPI (as far as I know). @goanpeca, could you please upload it?

Please be aware that you need at least Spyder 3.0 beta2 to run this plugin :-) I won't run in Spyder 2.3.x.

**Comment by Nodd** [comment]
The plugin infrastructure will change again (for the better!). I think we'll upload plugin packages when the change is merged in master.
