### ISSUE TITLE
Sorting by time / % not working correctly

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder.line_profiler#33]
First of all: This plugin is very useful, I'm using it a lot, thanks!

I discovered, that the sorting of results is not always working correctly. Do you know why this is the case? Or am I misinterpreting the display?

Sorting by `%`, I expect line 139 to be on top
![capture](https://user-images.githubusercontent.com/14980558/51170858-bf56f000-18af-11e9-95a4-2730a4f845cd.PNG)

Sorting by `Time`, I expect line 139 to be on top
![capture2](https://user-images.githubusercontent.com/14980558/51170860-c0881d00-18af-11e9-8bd1-00849145ca3a.PNG)

**Comment by ccordoba12** [comment]
This project is unmaintained right now, so a pull request to fix this problem is welcome.

**Comment by skjerns** [comment]
I've made a PR, problem seemed to be that items were inserted as strings, but sorting was on character level. I've implemented some natural sort in #34
