### ISSUE TITLE
Compatibility with Spyder 4.0

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder.line_profiler#37]
This package doesn't seem to be compatible with Spyder 4.0.0b.

The tab just doesn't show up.

Not sure if I'm the only one still using this library, but I consider it pretty useful.

Is there any way to easily embed it into Spyder 4?

**Comment by endolith** [comment]
> Not sure if I'm the only one still using this library

I would love to be able to do line profiling from within Spyder!

**Comment by jitseniesen** [comment]
> This package doesn't seem to be compatible with Spyder 4.0.0b.

The development version does work with Spyder 4 (as far as I know). I am hoping to do an official release this week.

**Comment by jitseniesen** [comment]
Version 0.2.0 of the plugin, which was just released, works with Spyder 4.
