### ISSUE TITLE
Standalone fork ?

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder.line_profiler#51]
Hello !
FYI I talked about spyder-line-profiler in https://github.com/pyutils/line_profiler/issues/55, but I didn't touch this addon since 2016 so I actually don't know in what state it is. It looks like it's maintained (last commit is from april 2020 and it's not like it needs frequent changes) but it doesn't run standalone anymore ?
If I find the time I'll try to play a bit with it, like in the good old days ;)

**Comment by ccordoba12** [comment]
Hey @Nodd!! Nice to hear from you again!

This plugin should be working just fine with Spyder 4, but not with 5.

**Comment by Nodd** [comment]
FYI, I started working on a standalone Qt interface : https://github.com/Nodd/lineprofilergui.
