### ISSUE TITLE
Spyder 5 compatibility

### ISSUE THREAD

**Issue by vastunghia** [spyder-ide/spyder.line_profiler#52]
Running `conda install spyder-line-profiler=0.2.1 -c spyder-ide` with Spyder 5.0.0 installed returns

```
The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (spyder):

  - spyder-line-profiler=0.2.1 -> spyder[version='>=4,<5']
```
Is spyder-line-profiler compatible with Spyder 5?

**Comment by ldorigo** [comment]
+1, would be great to have spyder 5 support.

**Comment by PasaOpasen** [comment]
succesfully run
```
conda install spyder-line-profiler -c spyder-ide
```
for spyder 5.0.2, but there is no "Profile by line" in Run window

**Comment by skjerns** [comment]
+1 for spyder 5 support! would be great!

I'd have a look at it.

However, it is expected that this works with both Spyder 4x and 5x? I think compatibility will be difficult. Or should we create an entirely new repo for 5x version?

**Comment by skjerns** [comment]
I've created a PR #53 that will enable support for Spyder 5 :) let me know if it works well for you!
