### ISSUE TITLE
Edit documentation to alert users to Spyder 5 incompatibility

### ISSUE THREAD

**Issue by NiftyVibe** [spyder-ide/spyder.line_profiler#55]
Hey, after messing around for while with the line profiler install, trying to figure out what I was doing wrong, I ended up here and can see there are a couple open issues on the lack of compatibility with Spyder 5. 
Right now, this plug-in still shows up in association with the Spyder 5 documentation, as shown below. It think it would be helpful if it included a warning box about the compatibility problems, to prevent other folks from sinking time into trying to get it running on 5.

![image](https://user-images.githubusercontent.com/40032266/149815503-10db4fe7-5fe7-4281-900d-027c789bf4c7.png)

I apologize for not just making the edit myself, but I was worried I would do something wrong. I don't know the general community protocols in Spyder for editing or if a compatibility warning is even something considered appropriate. Also, I'm a level 1 dabbler in programming, and it was not clear to me from reading these issues if some people are getting partial functionality or if everyone is getting nothing at all, like I am.  (None of the line profiling menu options show up at all for me, as if the line profiler isn't installed at all). So, I thought someone more familiar with the project should probably make whatever edits are appropriate.

**Comment by jitseniesen** [comment]
Hi, I am sorry about the time that you wasted. I will move your issue to the documentation repository. To be honest, I thought that documentation page that you showed has been removed (in PR spyder-ide/spyder-docs#283), but actually it was only removed from the left side bar.

I will let the documentation team decide how to handle this. I expect that a new version of the line-profiler plugin will come out within a month.

My understanding is that you should get nothing at all of the plugin functionality, but I did see reports of partial functionality. I don't know whether those users are confused or whether maybe the plugin does work with early versions of Spyder 5 or something like that.

**Comment by jitseniesen** [comment]
Issue moved to [spyder-ide/spyder-docs #304](https://github.com/spyder-ide/spyder-docs/issues/304) via [**ZenHub**](https://www.zenhub.com/)
