### ISSUE TITLE
Release spyder-line-profiler 0.3.0

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder.line_profiler#59]
An issue to track missing things to do before releasing 0.3.0 and also in case anyone has comments/questions regarding the release:

* [x] Update `README.md`
   * Should the installation commands be changed to use the conda-forge channel?
   * Update screenshot
* [x] Add a `RELEASE.md`
* [x] Update `CONTRIBUTING.rst` to `CONTRIBUTING.md` and add basic content to it
* [x] Missing default config for preferences/run action shortcut (probably doing something similar to [spyder-terminal](https://github.com/spyder-ide/spyder-terminal/blob/3f31677065707a28d2319738eb8c1027bde08503/spyder_terminal/terminalplugin.py#L46))
* [x] Define a better icon for the plugin (currently is a `.png`) -> `mdi-speedometer`
* [x] Should the `conda.recipe` directory be deleted?

Pinging @ccordoba12 and @jitseniesen just in case they have more things/comments/suggestions

**Comment by ccordoba12** [comment]
> Should the conda.recipe directory be deleted?

Yes, I think so.

**Comment by ccordoba12** [comment]
@dalthviz, I suggest to change the icon used by this plugin to be `mdi-speedometer`. That way we'll use here an icon that matches the others used in Spyder.

**Comment by dalthviz** [comment]
>I suggest to change the icon used by this plugin to be mdi-speedometer. That way we'll use here an icon that matches the others used in Spyder.

For that we will need to add the icon over Spyder on the `icon_manager.py`, right?

**Comment by ccordoba12** [comment]
No, you can use the QtAwesome API directly.

**Comment by dalthviz** [comment]
So seems like a release could be possible now! How wants to do the release @ccordoba12 @jitseniesen ?

**Comment by ccordoba12** [comment]
@dalthviz, I'd like you to do it because I don't have much free time these days. But I can't add more people to this project on PyPI (prbably @jitseniesen is the owner). So, I'll do it during the weekend unless someone else beats me to it.

**Comment by jitseniesen** [comment]
I will take care of the release today and tomorrow and add @dalthviz as a maintainer.

**Comment by dalthviz** [comment]
Thanks @jitseniesen !

**Comment by jitseniesen** [comment]
Closing because the release is out.

**Comment by ccordoba12** [comment]
Thanks @skjerns, @dalthviz and @jitseniesen for your help to update this plugin!
