### ISSUE TITLE
Update LICENSE.txt to match individual file copyright statements

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder.line_profiler#74]
The LICENSE.txt file currently reads:
https://github.com/spyder-ide/spyder-line-profiler/blob/6ab3eabb4de8491367ad817a9ac3a6d2c8c339d9/LICENSE.txt#L3
However, there are several different copyright statements in the individual files, for example setup.py has 2022 Spyder Project Contributors, while most others have 2021 or 2022 or 2022- Spyder Line Profiler Contributors.
It would be good to make the LICENSE.txt file consistent with the individual license statements within the source code.

**Comment by jitseniesen** [comment]
> However, there are several different copyright statements in the individual files, for example setup.py has 2022 Spyder Project Contributors, while most others have 2021 or 2022 or 2022- Spyder Line Profiler Contributors.

@juliangilbey Is the problem that the year is not the same or the designation of the copyright holders ("Spyder Project Contributors" versus "Spyder Line Profiler Contributors")? Or both?

**Comment by juliangilbey** [comment]
Hi @jitseniesen, the key issue is the designation of the copyright holders in the LICENSE.txt file not matching the files in the package, though updating the years for consistency would be nice too.
