### ISSUE TITLE
Expand output by default if only one function is profiled

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder.line_profiler#8]
from https://github.com/Nodd/spyder_line_profiler/issues/23

> In the output, if only a single function is profiled, I think it would be nice if it was expanded by default.

**Comment by ccordoba12** [comment]
@Nodd, quick question: any time frame or milestone for when you plan to fix these and the other issues you opened?

**Comment by Nodd** [comment]
I'm sorry I can't give you a time frame, I just have to find the time someday... I'll at least wait for the new plugin loading mode (either doing it myself or waiting for @goanpeca to do it) to do many things in one go.
